# Generated by Django 6.0.2 on 2026-03-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade',
            new_name='estoque',
        ),
    ]
