# Generated by Django 5.2.11 on 2026-03-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=11)),
                ('produto', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('valor_encomenda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('data_pedido', models.DateTimeField()),
                ('data_entrega', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientes.cliente')),
            ],
        ),
    ]
