# Generated by Django 6.0.2 on 2026-03-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('produtos', '0002_alter_produto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cpf_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_encomenda',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
